---
name: NotificationAlert
on: workflow_dispatch 
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step1 in job1
        run: echo "Hello"
  job2:
    needs: job1
    runs-on: ubuntu-24.04
    steps:
      - name: step2 in job2
        run: |
          hostname -s
          echo "Thankyou"
          
